### ISSUE TITLE
FR-042 Role Assistance

### ISSUE THREAD

**Issue by lorddusk** [CrawlerEmporium/DiscordCrawler#3]
**Feature Request:** Role Assistance

**Who would use it?** Admins (and users)
**How would it work?** [`!role ["text field"] [role name] [emoji/reaction],[role name] [emoji/reaction], etc ]

**Why should this be added?** Help grant roles 

(small addition - this Set should be a command to setup - and it should setup the roles at the same time for the server)

- Modnar#2707

> Upvote - Joanne#0666

> Upvote - Aghanim#0001

> Upvote - Modnar#2707

Votes: +3 / -0

**Comment by crawltracker** [comment]
Note - LordDusk#0001

Resolved - Added to <@602774912595263490> as ``add/removeRole``

**Comment by crawltracker** [comment]
Note - LordDusk#0001

Resolved - Added to <@602774912595263490> as add/removeRole
